---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: searxng-secret
  namespace: homelab-ai
spec:
  encryptedData:
    secret-key: AgBLq3HQUR8rYFNd/KyGMWUMrpKkICi6HlnAAeM+FwKSxQ24FL7pQAyIPKP0NrKS75icNN9JiQOO0SCLjNidnL3PF483hXvIhPa6i/BEPekUsP5d40zHR82qObZ+wHfK/dVG5y+OlvKEpsVBq64eM0rqyP9aU+P9TFK5IGBsJsOWjwqAkVpCOvQJzIBLXqJikERWb2xgQl/l/XYBCogVg39BWsvNyX0Nfv13zCNfnL/nvt9RKl8Z1BPC6w+Pnt1K+BQmg9k9jdxzVT7rxrveuFrUWe8NQxSp32tjan/K5J1PCFHQsAlsoT6yqB7B6YKpSQ9ys0+Q3PYOqdEXQOcb9tb55R5FaoUzDAHH8CM+TyG3nu/VLjMW4TgY1J0tlCI6vM43iM9eufYlIXfB4mRm9ElpihALsOZ02W6AwY/DTCP+qQaEC3zMgb8/VoR5lvgeuM1cNZS0MtExqEzjo/+STHWxk2H96QVs/DhX86JmA5R/15PgugY/7daWdreH4F/uCNJUX4JHu2jzwiLqOmZlyH9+IDpXMSFkI9D3htZW0vTxKv84m7xumyMoA6st8dZapvywQxo6/QwxF659UiswKO2iumSaKlNAA8hKFMyyN9HymqqdakzQiYuj49lioyP/6Gcwn4T35yfqb1DGU84TPmGXuvBeAozTU1zwRgcrSFnaA19v7xbcaFIIkSIgAEMZy0TBhh2edrTFBIoxIw4AMu2lsH2B7X2dJ4IJBTDV4MwD2LnmrSW2qOPRbdaZMo/07zWf6fESOph943G+L79vPfPc
  template:
    metadata:
      creationTimestamp: null
      name: searxng-secret
      namespace: homelab-ai
