---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openwebui-admin-secret
  namespace: homelab-ai
spec:
  encryptedData:
    email: AgAruOy12OWrCugHns++usI6FNCf14b07ay+qfQDblWrtk7lPAoSjfwsX9UKxHqaYoKsaAqWiojnHhqWw7RPOtXF/eKrje1VL0uqpa0UJcGnyPjpaPWa/cdgS/qybk8AF3KMfzPddeO8Oom2vlXSP3TVg43oSVQtwajlshyiYxi+nDNqfcw05MNljJOBn7MZggYek5Xhqwz1NpAn4miLzaakJQyJ364kLtj2nmZl1KjsizWPcogBTjoD8JBKyV+l0joML4TAtse63w05fOj/eyiyWYVh/0oril9GklQWD5AH81hqBgTMelvmvFo0/07TgeG/SlPMaDqZ5ETdSp/AMMeAh2Kj+R8YP4ojG9VVLe1jEcTRkvo2tWPAUnfTHvk2xe0s3ncswPvH4IibJWS0kKZ8u4wrEca9NmfoIun3ofc29C+lpmjgXn6h7ZdF1W43RNwXQcDpuTD1CEKUlN7OI7Se5KEm47hj7uvnqziGh5f1W4H42uylnRZ11n/bAaUoVh8ZxHnZ6vDTpoL9mbr5BXC/U39nkNot43uO3VVwc6/rvVI2tg2lxtMZJUv6rR9pcPz/D9NNifexTPeQvgJ5nHoNgJJNxYs4ekCegzXl/qjsfNouuJBSGRcFAncSViYL+Cqng91nOTws0MMZjL7zsf05ZYcMkThuBiuwKOOR4xe+0tb66qbKF2wuPiioJSnjtCtV0y+BEYB5IEOhWN4rr19WJRo=
    password: AgCvy8lE9mfVXEBUvHF20z3vqGfMBASvMH1plJ2xBDVyy8PEe+6vYigGiH9I7p8MxnUMJMWPbR1R+O6qBdUwJ+0GGVidx/SNHk872gOizSgYcg8vDDuOKqlo70566iiphMfUsVprCJZMWwBxBcABwbCuJPzdGSnIueAx5NkwK3kuJLOqwDE3srXd+XD1LX+drUXy7vGDUovggiyWwd/UFX3cTVSPPFGPHp3nViWcdMkfFE/TFCWfcKvFp7AnyLhrsntnsRaev9dtzReIWRffpCUIfiCglwmltU2Nb3QUcmR12AJkSgxuWn3yAFYAcCAqBvePniAqOfelbHg7ZP0+0m9lKSPhKWzp4BueCdCcIMfeRyLXzqbuGS5nT6Wt2K9qXXvMy9abw+6vxNGPtaxfWCo/1UVMkh+vXWtJupv8LhMzdDMRfaMMIuBI9C516wk1ln1vGI9CUgpi9nReTc1ecAUKUhUmdXJ2K7/8Aa9p8NGccn/DHOHxITvtdYD3+dCOA/nEYu77OA/IHhj62aA2+ulUTNidsD1a8mkkBCRndH1UdZ1jFSiF6HnZiuH2p/x5PPcFB1zB9OD431ahgSV8jW9Spqn09h41GSAGm8M7/0IkiNKDrYy2oyGlt0+TgZ9KxBeJn7BqnLWL+YmJ2D0yeKhIRkmKsdhWxAzNl6QAoRa5O1QaNiqnSPi7VtnpWu4jVvC0APD9sdjcwzQ12gbW
  template:
    metadata:
      creationTimestamp: null
      name: openwebui-admin-secret
      namespace: homelab-ai
